# Generated by Django 4.1.3 on 2022-11-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='gallery',
            field=models.ManyToManyField(to='hospital_news.newsgallerymodel', verbose_name='گالری خبر'),
        ),
    ]
