# Generated by Django 4.1.3 on 2023-01-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsgallerymodel',
            old_name='title_ar',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='newsgallerymodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='newsgallerymodel',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='newsgallerymodel',
            name='title_ru',
        ),
    ]
