# Generated by Django 4.1.3 on 2023-02-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='is_emailed',
            field=models.BooleanField(default=False, editable=False, verbose_name='آیا ایمیل شده است؟'),
        ),
    ]
