# Generated by Django 4.1.3 on 2023-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_news', '0002_rename_title_ar_newsgallerymodel_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscommentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newslikemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='newscommentmodel',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='newscommentmodel',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='newscommentmodel',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='newslikemodel',
            name='user_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
