# Generated by Django 4.1.3 on 2023-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_news', '0002_alter_newsmodel_is_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='is_publish',
            field=models.BooleanField(default=False, help_text='اگر این تیک فعال باشد بعد از ذخیره شدن ایمیل برای اعضای خبرنامه ارسال میشود.', verbose_name='آیا منتشر شود؟'),
        ),
    ]
