# Generated by Django 4.1.3 on 2023-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_news', '0004_alter_newscommentmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
