# Generated by Django 4.1.3 on 2022-12-31 13:23

from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCodePatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uidb64', models.CharField(blank=True, max_length=255, null=True, verbose_name='uidb64')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='token')),
                ('doctor_medical_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد نظام پزشکی پزشک مربوطه')),
                ('appointment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='آیدی زمان نوبت دهی انتخاب شده')),
                ('patient_turn_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='آیدی نوبت بیمار')),
                ('phone', models.CharField(max_length=30, verbose_name='شماره تلفن')),
                ('code', models.IntegerField(default=extentions.utils.get_random_code, verbose_name='کد')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید کد')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای کد')),
                ('is_use', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
            ],
            options={
                'verbose_name': 'کد ارسال شده به شماره بیمار',
                'verbose_name_plural': 'کدهای ارسال شده به شماره بیماران ',
                'ordering': ['-id'],
            },
        ),
    ]
