# Generated by Django 4.1.3 on 2023-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logincodepatientmodel',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='logincodepatientmodel',
            name='doctor_medical_code',
        ),
        migrations.RemoveField(
            model_name='logincodepatientmodel',
            name='patient_turn_id',
        ),
        migrations.RemoveField(
            model_name='logincodepatientmodel',
            name='token',
        ),
        migrations.RemoveField(
            model_name='logincodepatientmodel',
            name='uidb64',
        ),
        migrations.AddField(
            model_name='logincodepatientmodel',
            name='expire_mission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای عملیات'),
        ),
    ]
