# Generated by Django 4.1.3 on 2022-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_website', '0002_remove_logincodepatientmodel_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincodepatientmodel',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آیدی زمان نوبت دهی انتخاب شده'),
        ),
        migrations.AddField(
            model_name='logincodepatientmodel',
            name='doctor_medical_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد نظام پزشکی پزشک مربوطه'),
        ),
        migrations.AddField(
            model_name='logincodepatientmodel',
            name='patient_turn_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آیدی نوبت بیمار'),
        ),
        migrations.AddField(
            model_name='logincodepatientmodel',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='logincodepatientmodel',
            name='uidb64',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='uidb64'),
        ),
    ]
