# Generated by Django 4.1.3 on 2022-12-06 10:58

from django.db import migrations, models
import django.db.models.manager
import extentions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=extentions.utils.certificate_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=extentions.utils.costs_image_path, verbose_name='تصویر')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
            ],
            options={
                'verbose_name': 'ارزش بیمارستان',
                'verbose_name_plural': 'ارزش های بیمارستان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'سوال پر تکرار',
                'verbose_name_plural': 'سوالات پر تکرار',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HomeGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='متن')),
                ('image', models.ImageField(upload_to=extentions.utils.home_gallery_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'آیتم گالری صفحه ی خانه',
                'verbose_name_plural': 'آیتم های گالری صفحه ی خانه',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalFacilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=extentions.utils.facility_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'امکانات بیمارستان',
                'verbose_name_plural': 'امکانات های بیمارستان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalGalleryItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('file_type', models.CharField(choices=[('video', 'ویدیو'), ('image', 'تصویر')], max_length=20, verbose_name='نوع فایل')),
                ('file', models.FileField(upload_to=extentions.utils.gallery_image_path, verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'آیتم گالری',
                'verbose_name_plural': 'آیتم های گالری',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalPoliticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'سیاست بیمارستان',
                'verbose_name_plural': 'سیاست های بیمارستان',
                'ordering': ['-id'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InsuranceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام بیمه')),
            ],
            options={
                'verbose_name': 'بیمه طرف قرارداد',
                'verbose_name_plural': 'بیمه های طرف قرارداد',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'خبرنامه',
                'verbose_name_plural': 'خبرنامه',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('type_service', models.CharField(max_length=500, verbose_name='نوع خدمت')),
            ],
            options={
                'verbose_name': 'تعرفه',
                'verbose_name_plural': 'تعرفه ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_bound', models.CharField(max_length=100, verbose_name='مدت عملکرد')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=extentions.utils.gallery_image_path, verbose_name='تصویر')),
                ('video', models.FileField(upload_to=extentions.utils.gallery_image_path, verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'گزارش بیمارستان',
                'verbose_name_plural': 'گزارش های بیمارستان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دستاورد بیمارستان',
                'verbose_name_plural': 'دستاورد های بیمارستان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_scale', models.FloatField(blank=True, null=True, verbose_name='مقیاس ایکس')),
                ('y_scale', models.FloatField(blank=True, null=True, verbose_name='مقیاس ایگرگ')),
                ('marker_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن شما روی نقشه')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=255, verbose_name='تلفن')),
                ('from_to', models.CharField(max_length=200, verbose_name='زمان گشایش')),
                ('history', models.TextField(verbose_name='تاریخچه')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='لینکدین')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='فیسبوک')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='توییتر')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='واتساپ')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بانک')),
                ('bank_account_owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام صاحب حساب')),
                ('bank_account_cardnum', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره کارت')),
                ('bank_account_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره حساب')),
                ('bank_account_shabanum', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره شبا')),
            ],
            options={
                'verbose_name': '\u200cتنظیمات',
                'verbose_name_plural': '\u200cتنظیمات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('items', models.ManyToManyField(to='hospital_setting.hospitalgalleryitemmodel', verbose_name='آیتم/آیتم ها')),
            ],
            options={
                'verbose_name': 'گالری بیمارستان',
                'verbose_name_plural': 'گالری های بیمارستان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalPoliticRECYCLE',
            fields=[
            ],
            options={
                'verbose_name': 'سیاست بیمارستان - بازیابی',
                'verbose_name_plural': 'سیاست های بیمارستان - بازیابی',
                'ordering': ['-id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hospital_setting.hospitalpoliticmodel',),
            managers=[
                ('deleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
