# Generated by Django 4.1.3 on 2022-12-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceappointmentmodel',
            name='price_free',
        ),
        migrations.RemoveField(
            model_name='priceappointmentmodel',
            name='price_insurance',
        ),
        migrations.RemoveField(
            model_name='priceappointmentmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='priceappointmentmodel',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
