# Generated by Django 4.1.3 on 2022-12-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebedmodel',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_setting.insurancemodel', verbose_name='بیمه'),
        ),
        migrations.AddField(
            model_name='pricesurgraymodel',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_setting.insurancemodel', verbose_name='بیمه'),
        ),
        migrations.AlterField(
            model_name='pricebedmodel',
            name='price_free',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ آزاد'),
        ),
        migrations.AlterField(
            model_name='pricebedmodel',
            name='price_insurance',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ بیمه'),
        ),
        migrations.AlterField(
            model_name='pricesurgraymodel',
            name='price_free',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ آزاد'),
        ),
        migrations.AlterField(
            model_name='pricesurgraymodel',
            name='price_insurance',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ بیمه'),
        ),
    ]
