# Generated by Django 4.1.3 on 2023-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmodel',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='فکس'),
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تلگرام'),
        ),
    ]
