# Generated by Django 4.1.3 on 2023-01-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancemodel',
            old_name='title_ar',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='newslettermodel',
            old_name='desc_ar',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='newslettermodel',
            old_name='title_ar',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='insurancemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='insurancemodel',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='insurancemodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='newslettermodel',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='newslettermodel',
            name='desc_fa',
        ),
        migrations.RemoveField(
            model_name='newslettermodel',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='newslettermodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='newslettermodel',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='newslettermodel',
            name='title_ru',
        ),
    ]
