# Generated by Django 4.1.3 on 2023-01-08 19:50

from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=extentions.utils.ancient_image_path, verbose_name='تصویر')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام پزشک مرحوم')),
                ('description', models.TextField(verbose_name='متن')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک ویدیو')),
                ('gallery', models.ManyToManyField(to='hospital_setting.hospitalgalleryitemmodel', verbose_name='گالری')),
            ],
            options={
                'verbose_name': 'گذشتگان بیمارستان',
                'verbose_name_plural': 'گذشتگان بیمارستان',
                'ordering': ['-id'],
            },
        ),
    ]
