# Generated by Django 4.1.3 on 2022-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalpoliticmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
