# Generated by Django 4.1.3 on 2022-12-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0002_pricebedmodel_insurance_pricesurgraymodel_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebedmodel',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.insurancemodel', verbose_name='بیمه'),
        ),
    ]
