# Generated by Django 4.1.3 on 2022-12-03 10:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0002_hospitalpoliticmodel_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPoliticRECYCLE',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hospital_setting.hospitalpoliticmodel',),
            managers=[
                ('deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='hospitalpoliticmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalpoliticmodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
