# Generated by Django 4.1.3 on 2022-12-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0003_hospitalpoliticrecycle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalpoliticmodel',
            options={'default_manager_name': 'objects', 'ordering': ['-id'], 'verbose_name': 'سیاست بیمارستان', 'verbose_name_plural': 'سیاست های بیمارستان'},
        ),
        migrations.AlterModelOptions(
            name='hospitalpoliticrecycle',
            options={'ordering': ['-id'], 'verbose_name': 'سیاست بیمارستان - بازیابی', 'verbose_name_plural': 'سیاست های بیمارستان - بازیابی'},
        ),
    ]
