# Generated by Django 4.1.3 on 2023-04-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0003_remove_settingmodel_facs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homegallerymodel',
            old_name='title_ar',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='homegallerymodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homegallerymodel',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='homegallerymodel',
            name='title_ru',
        ),
    ]
