# Generated by Django 4.1.3 on 2023-04-16 12:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0004_rename_title_ar_homegallerymodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmodel',
            name='aboutus_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='aboutus_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='aboutus_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='settingmodel',
            name='aboutus_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
    ]
