# Generated by Django 4.1.3 on 2023-01-05 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_setting', '0001_initial'),
        ('hospital_units', '0001_initial'),
        ('hospital_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='insurances',
            field=models.ManyToManyField(to='hospital_setting.insurancemodel', verbose_name='بیمه ها'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='skill_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.titleskillmodel', verbose_name='عنوان تخصص'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
