# Generated by Django 4.1.3 on 2022-12-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
        ('hospital_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorskillmodel',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_units.clinicmodel', verbose_name='کلینیک'),
        ),
        migrations.DeleteModel(
            name='ClinicModel',
        ),
    ]
