# Generated by Django 4.1.3 on 2022-12-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorworktimemodel',
            name='day',
        ),
        migrations.AddField(
            model_name='doctorworktimemodel',
            name='day_from',
            field=models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک شنبه'), ('monday', 'دو شنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهار شنبه'), ('thursday', 'پنج شنبه'), ('friday', 'جمعه')], default='saturday', max_length=15, verbose_name='از روز'),
        ),
        migrations.AddField(
            model_name='doctorworktimemodel',
            name='day_to',
            field=models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک شنبه'), ('monday', 'دو شنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهار شنبه'), ('thursday', 'پنج شنبه'), ('friday', 'جمعه')], default='thursday', max_length=15, verbose_name='تا روز'),
        ),
    ]
