# Generated by Django 4.1.3 on 2022-12-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_doctor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.degreemodel', verbose_name='نوع مدرک'),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='skill_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.titleskillmodel', verbose_name='عنوان تخصص'),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='doctorvacationmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='doctorworktimemodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک'),
        ),
    ]
