# Generated by Django 4.1.3 on 2023-02-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_doctor', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamousPatientModel',
        ),
    ]
