# Generated by Django 4.1.3 on 2022-12-13 20:44

from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_doctor', '0003_alter_doctormodel_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('profile', models.ImageField(upload_to=extentions.utils.profile_image_path, verbose_name='تصویر')),
                ('desc', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'چهره سرشناس مراجعه کننده',
                'verbose_name_plural': 'چهره های سرشناس مراجعه کننده',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InternationalPatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
            ],
            options={
                'verbose_name': 'بیمار بین الملل',
                'verbose_name_plural': 'بیماران بین الملل',
                'ordering': ['-id'],
            },
        ),
    ]
