# Generated by Django 4.1.3 on 2022-12-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_doctor', '0003_doctormodel_isinstances_delete_doctorinsurancemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormodel',
            old_name='isinstances',
            new_name='insurances',
        ),
    ]
