# Generated by Django 4.1.3 on 2022-12-18 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import extentions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_setting', '0001_initial'),
        ('hospital_doctor', '0001_initial'),
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ روز')),
                ('day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک شنبه'), ('monday', 'دو شنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهار شنبه'), ('thursday', 'پنج شنبه'), ('friday', 'جمعه')], max_length=15, verbose_name='روز')),
                ('time_from', models.CharField(choices=[('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('24:00', '24:00')], max_length=15, verbose_name='از ساعت')),
                ('time_to', models.CharField(choices=[('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('24:00', '24:00')], max_length=15, verbose_name='تا ساعت')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت کل')),
                ('reserved', models.PositiveIntegerField(verbose_name='تعداد رزرو شده')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.priceappointmentmodel', verbose_name='تعرفه')),
            ],
            options={
                'verbose_name': 'زمان نوبتدهی',
                'verbose_name_plural': 'زمان های نوبتدهی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentTipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='عنوان')),
                ('tips', models.TextField(verbose_name='نکات')),
            ],
            options={
                'verbose_name': 'نکات نوبت دهی',
                'verbose_name_plural': 'نکات نوبت دهی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LimitTurnTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_hour', models.PositiveIntegerField(verbose_name='تا ساعت چند؟')),
                ('how_days_hour', models.PositiveIntegerField(verbose_name='چند روز قبل؟ (به ساعت)')),
            ],
            options={
                'verbose_name': 'حد زمانی برای انتخاب نوبت',
                'verbose_name_plural': 'حد زمانی برای انتخاب نوبت',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'عنوان بخش',
                'verbose_name_plural': 'عناوین بخش',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medical', 'درمانی'), ('paraclinic', 'پاراکلینیک'), ('official', 'غیردرمانی')], max_length=255, verbose_name='دسته بندی بخش')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
                ('have_appointment', models.BooleanField(default=False, verbose_name='امکان نوبت دهی آنلاین دارد؟')),
                ('desc', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to=extentions.utils.units_image_path, verbose_name='تصویر')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='تلفن')),
                ('inside', models.PositiveIntegerField(blank=True, null=True, verbose_name='داخلی')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('work_times', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعات کاری')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='مسیول')),
                ('manager_phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='شماره مسیول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('subunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.subunitmodel', verbose_name='عنوان بخش')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=7, verbose_name='جنسیت')),
                ('job', models.CharField(max_length=255, verbose_name='سمت')),
                ('profile', models.ImageField(blank=True, null=True, upload_to=extentions.utils.unit_member_image_path, verbose_name='پروفایل')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientTurnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=extentions.utils.code_patient_turn, max_length=15, verbose_name='کد پیگیری نوبت')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام بیمار')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی بیمار')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کدملی بیمار')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='شماره تلفن بیمار')),
                ('age', models.PositiveIntegerField(verbose_name='سن بیمار')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=7, verbose_name='جنسیت بیمار')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ قابل پرداخت')),
                ('prescription_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='کد نسخه ی پزشک دیگر')),
                ('experiment_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='کدرهگیری(کدملی)')),
                ('turn', models.PositiveIntegerField(blank=True, null=True, verbose_name='نوبت فیزیکی بیمار')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='آیا از مبلغ کنسل شدن به بیمار واریز شده است؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.appointmenttimemodel', verbose_name='زمان مشاوره')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.insurancemodel', verbose_name='بیمه')),
            ],
            options={
                'verbose_name': 'نوبت بیمار',
                'verbose_name_plural': 'نوبت بیماران',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OnlinePaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ پرداختی')),
                ('is_success', models.BooleanField(default=False, verbose_name='آیا تراکنش موفقیت آمیز بوده است؟')),
                ('code', models.CharField(max_length=50, verbose_name='شماره پرداخت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.patientturnmodel', verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'پرداخت اینترنتی',
                'verbose_name_plural': 'پرداخت های اینترنتی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExprimentResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('experiment', 'آزمایش'), ('ctscan', 'تصویربرداری (سی تی اسکن)'), ('radiography_simple', 'تصویربرداری (رادیوگرافی ساده)'), ('radiography_special', 'تصویربرداری (رادیوگرافی تخصصی)'), ('mamography', 'تصویربرداری (ماموگرافی)'), ('sonography', 'تصویربرداری (سونوگرافی)')], max_length=20, verbose_name='نوع نتیجه')),
                ('code', models.CharField(default=extentions.utils.get_experiment_code, max_length=20, unique=True, verbose_name='کد پیگیری')),
                ('is_show_send_sms', models.BooleanField(default=False, verbose_name='بعد از ذخیره کردن آیا نمایش داده شود و پیامک به کاربر ارسال شود؟')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آزمایش')),
                ('result', models.CharField(max_length=255, verbose_name='جواب آزمایش')),
                ('image', models.ImageField(upload_to=extentions.utils.experiment_result_image_path, verbose_name='تصویر آزمایش')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نتیجه')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.insurancemodel', verbose_name='بیمه')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_auth.patientmodel', verbose_name='بیمار')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'نتیجه آزمایش و تصویربرداری',
                'verbose_name_plural': 'نتیجه آزمایش ها و تصویربرداری ها',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='appointmenttimemodel',
            name='tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.appointmenttipmodel', verbose_name='نکات نوبت دهی'),
        ),
        migrations.AddField(
            model_name='appointmenttimemodel',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='اگر مقداری به این قسمت داده نشود در اینصورت بخش پزشکان انتخاب میشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش'),
        ),
    ]
