# Generated by Django 4.1.3 on 2023-03-15 21:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hospital_extentions.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_setting', '0001_initial'),
        ('hospital_auth', '0001_initial'),
        ('hospital_doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTimeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ روز')),
                ('day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک\u200cشنبه'), ('monday', 'دو\u200cشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهار\u200cشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه')], max_length=15, verbose_name='روز')),
                ('time_from', models.CharField(choices=[('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('24:00', '24:00')], max_length=15, verbose_name='از ساعت')),
                ('time_to', models.CharField(choices=[('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('24:00', '24:00')], max_length=15, verbose_name='تا ساعت')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت کل')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='تعداد رزرو شده')),
                ('status', models.CharField(choices=[('invac', 'مرخصی پزشک'), ('normal', 'معمولی')], default='normal', max_length=15, verbose_name='وضعیت')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک')),
                ('insurances', models.ManyToManyField(to='hospital_setting.insurancemodel', verbose_name='بیمه\u200cها')),
            ],
            options={
                'verbose_name': 'زمان نوبت\u200cدهی',
                'verbose_name_plural': 'زمان\u200cهای نوبت\u200cدهی',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentTipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('tips', ckeditor.fields.RichTextField(verbose_name='نکات')),
            ],
            options={
                'verbose_name': 'نکات نوبت\u200cدهی',
                'verbose_name_plural': 'نکات نوبت\u200cدهی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentTipSMSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('tips', models.TextField(verbose_name='نکات')),
            ],
            options={
                'verbose_name': 'نکات نوبت\u200cدهی در پیامک',
                'verbose_name_plural': 'نکات نوبت\u200cدهی در پیامک',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LimitTurnTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='تا چند ساعت قبل؟')),
                ('rules', ckeditor.fields.RichTextField(blank=True, help_text='این قوانین در صفحه\u200cی اول قبل از انجام مراحل رزرو اینترنتی نمایش داده میشود.', null=True, verbose_name='قوانین نوبت\u200cدهی')),
            ],
            options={
                'verbose_name': 'حد\u200cزمانی برای انتخاب نوبت',
                'verbose_name_plural': 'حد\u200cزمانی برای انتخاب نوبت',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoginCodePatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='شماره تلفن')),
                ('code', models.IntegerField(default=hospital_extentions.utils.get_random_code, verbose_name='کد')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید کد')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای کد')),
                ('is_use', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
                ('expire_mission', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای عملیات')),
            ],
            options={
                'verbose_name': 'کد ارسال شده به شماره بیمار',
                'verbose_name_plural': 'کدهای ارسال شده به شماره بیماران ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ManagersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('hm', 'هیات مدیره'), ('magm', 'مدیرعامل و گروه مدیریت')], max_length=255, verbose_name='دسته\u200cبندی نمایش')),
                ('first_name_fa', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_en', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_ar', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_ru', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name_fa', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('last_name_en', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('last_name_ar', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('last_name_ru', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=7, verbose_name='جنسیت')),
                ('job_fa', models.CharField(max_length=255, verbose_name='سمت')),
                ('job_en', models.CharField(max_length=255, verbose_name='سمت')),
                ('job_ar', models.CharField(max_length=255, verbose_name='سمت')),
                ('job_ru', models.CharField(max_length=255, verbose_name='سمت')),
                ('profile', models.ImageField(blank=True, null=True, upload_to=hospital_extentions.utils.managers_image_path, verbose_name='پروفایل')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینکدین')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='فیسبوک')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='توییتر')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='اینستاگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='واتساپ')),
            ],
            options={
                'verbose_name': 'مدیریت بیمارستان',
                'verbose_name_plural': 'مدیریت بیمارستان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=hospital_extentions.utils.get_links_code, unique=True, verbose_name='نمایش در url')),
                ('category', models.CharField(choices=[('medical', 'درمانی'), ('paraclinic', 'پاراکلینیک'), ('official', 'غیردرمانی')], max_length=255, null=True, verbose_name='دسته بندی بخش')),
                ('title_fa', models.CharField(max_length=255, verbose_name='نام')),
                ('title_en', models.CharField(max_length=255, verbose_name='نام')),
                ('title_ar', models.CharField(max_length=255, verbose_name='نام')),
                ('title_ru', models.CharField(max_length=255, verbose_name='نام')),
                ('have_2_box', models.BooleanField(default=False, help_text='در بخش نوبت\u200cدهی اینترنتی باعث میشود که کاربر به ۲ طریق مختلف رزرو اینترنتی انجام دهد.', verbose_name='آیا دو قسمتی است؟')),
            ],
            options={
                'verbose_name': 'عنوان بخش',
                'verbose_name_plural': 'عناوین بخش',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('desc_fa', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('desc_en', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('desc_ar', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('desc_ru', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hospital_extentions.utils.units_image_path, verbose_name='تصویر')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='تلفن')),
                ('inside', models.PositiveIntegerField(blank=True, null=True, verbose_name='داخلی')),
                ('address_fa', models.CharField(max_length=255, verbose_name='آدرس')),
                ('address_en', models.CharField(max_length=255, verbose_name='آدرس')),
                ('address_ar', models.CharField(max_length=255, verbose_name='آدرس')),
                ('address_ru', models.CharField(max_length=255, verbose_name='آدرس')),
                ('work_times', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعات کاری')),
                ('manager_fa', models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول')),
                ('manager_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول')),
                ('manager_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول')),
                ('manager_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول')),
                ('manager_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره مسئول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=hospital_extentions.utils.units_icon_image_path, verbose_name='آیکون بخش')),
                ('subunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.subunitmodel', verbose_name='عنوان بخش')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_fa', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_en', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_ar', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_ru', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name_fa', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('last_name_en', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('last_name_ar', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('last_name_ru', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('phone', models.CharField(default=0, max_length=100, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=7, verbose_name='جنسیت')),
                ('job_fa', models.CharField(max_length=255, verbose_name='سمت')),
                ('job_en', models.CharField(max_length=255, verbose_name='سمت')),
                ('job_ar', models.CharField(max_length=255, verbose_name='سمت')),
                ('job_ru', models.CharField(max_length=255, verbose_name='سمت')),
                ('profile', models.ImageField(blank=True, null=True, upload_to=hospital_extentions.utils.unit_member_image_path, verbose_name='پروفایل')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'عضو بخش',
                'verbose_name_plural': 'اعضای بخش\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientTurnModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default=hospital_extentions.utils.code_patient_turn, max_length=15, verbose_name='کد پیگیری نوبت')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ قابل پرداخت')),
                ('prescription_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='کد نسخه\u200cی پزشک دیگر')),
                ('experiment_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='کدرهگیری(کدملی)')),
                ('turn', models.PositiveIntegerField(blank=True, null=True, verbose_name='نوبت فیزیکی بیمار')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='آیا از سمت بیمار کنسل شده است؟')),
                ('is_returned', models.BooleanField(default=False, verbose_name='آیا مبلغ کنسل شدن به بیمار واریز شده است؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.appointmenttimemodel', verbose_name='زمان مشاوره')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.insurancemodel', verbose_name='بیمه')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_auth.patientmodel', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نوبت بیمار',
                'verbose_name_plural': 'نوبت بیماران',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OnlinePaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ پرداختی')),
                ('is_success', models.BooleanField(default=False, verbose_name='آیا تراکنش موفقیت\u200cآمیز بوده است؟')),
                ('code', models.CharField(max_length=50, verbose_name='شماره پرداخت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.patientturnmodel', verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'پرداخت اینترنتی',
                'verbose_name_plural': 'پرداخت\u200cهای اینترنتی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExprimentResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=hospital_extentions.utils.get_experiment_code, max_length=20, unique=True, verbose_name='کد پیگیری')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آزمایش')),
                ('result', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='جواب آزمایش')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hospital_extentions.utils.experiment_result_image_path, verbose_name='تصویر آزمایش')),
                ('date', models.DateField(blank=True, null=True, verbose_name='زمان ثبت نتیجه')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_auth.patientmodel', verbose_name='بیمار')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'نتیجه آزمایش و تصویربرداری',
                'verbose_name_plural': 'نتیجه آزمایش\u200cها و تصویربرداری\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicPrescriptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('experiment_code', models.CharField(max_length=30, verbose_name='کدرهگیری(کدملی)')),
                ('selected_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نوبت')),
                ('selected_time', models.CharField(blank=True, choices=[('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('24:00', '24:00')], max_length=15, null=True, verbose_name='ساعت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False, verbose_name='آیا این نوبت ثبت شده است؟')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_auth.patientmodel', verbose_name='بیمار')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'نوبت نسخه\u200cی الکترونیکی بیمار',
                'verbose_name_plural': 'نوبت نسخه\u200cی الکترونیکی بیماران',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='appointmenttimemodel',
            name='tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.appointmenttipmodel', verbose_name='نکات نوبت\u200cدهی'),
        ),
        migrations.AddField(
            model_name='appointmenttimemodel',
            name='tip_sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.appointmenttipsmsmodel', verbose_name='نکات نوبت\u200cدهی در پیامک'),
        ),
        migrations.AddField(
            model_name='appointmenttimemodel',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='اگر مقداری به این قسمت داده نشود در اینصورت بخش پزشکان انتخاب میشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش'),
        ),
    ]
