# Generated by Django 4.1.3 on 2022-12-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsectionmodel',
            name='inside',
        ),
        migrations.RemoveField(
            model_name='treatmentsectionmodel',
            name='phone',
        ),
    ]
