# Generated by Django 4.1.3 on 2022-12-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitmembermodel',
            options={'ordering': ['-id'], 'verbose_name': 'عضو بخش', 'verbose_name_plural': 'اعضای بخش ها'},
        ),
    ]
