# Generated by Django 4.1.3 on 2022-12-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0001_initial'),
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitturntimemodel',
            name='how_days_hour',
        ),
        migrations.RemoveField(
            model_name='limitturntimemodel',
            name='to_hour',
        ),
        migrations.AddField(
            model_name='limitturntimemodel',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تا چند ساعت قبل؟'),
        ),
        migrations.AlterField(
            model_name='appointmenttimemodel',
            name='price',
            field=models.ForeignKey(blank=True, help_text='درصورت ندادن مقدار از جدول تعرفه ی نوبت دهی اطلاعات گیری میشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.priceappointmentmodel', verbose_name='تعرفه'),
        ),
    ]
