# Generated by Django 4.1.3 on 2022-12-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='insurance_code',
        ),
    ]
