# Generated by Django 4.1.3 on 2022-12-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientturnmodel',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='آیا مبلغ کنسل شدن به بیمار واریز شده است؟'),
        ),
        migrations.AlterField(
            model_name='patientturnmodel',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='آیا از سمت بیمار کنسل شده است؟'),
        ),
    ]
