# Generated by Django 4.1.3 on 2023-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttimemodel',
            name='status',
            field=models.CharField(choices=[('invac', 'مرخصی پزشک'), ('normal', 'معمولی')], default='normal', max_length=15, verbose_name='وضعیت'),
        ),
    ]
