# Generated by Django 4.1.3 on 2023-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exprimentresultmodel',
            old_name='is_show_send_sms',
            new_name='is_sent_sms',
        ),
        migrations.RemoveField(
            model_name='exprimentresultmodel',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='exprimentresultmodel',
            name='type',
        ),
        migrations.AlterField(
            model_name='exprimentresultmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان ثبت نتیجه'),
        ),
    ]
