# Generated by Django 4.1.3 on 2023-01-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttimemodel',
            options={'ordering': ['-date'], 'verbose_name': 'زمان نوبتدهی', 'verbose_name_plural': 'زمان های نوبتدهی'},
        ),
        migrations.AlterModelOptions(
            name='patientturnmodel',
            options={'ordering': ['-created'], 'verbose_name': 'نوبت بیمار', 'verbose_name_plural': 'نوبت بیماران'},
        ),
        migrations.RemoveField(
            model_name='unitmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='unitmodel',
            name='have_appointment',
        ),
        migrations.AddField(
            model_name='subunitmodel',
            name='category',
            field=models.CharField(choices=[('medical', 'درمانی'), ('paraclinic', 'پاراکلینیک'), ('official', 'غیردرمانی')], max_length=255, null=True, verbose_name='دسته بندی بخش'),
        ),
    ]
