# Generated by Django 4.1.3 on 2023-01-05 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import extentions.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
        ('hospital_setting', '0001_initial'),
        ('hospital_units', '0002_alter_appointmenttimemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicPrescriptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default=extentions.utils.code_patient_turn, max_length=15, verbose_name='کد پیگیری نوبت')),
                ('experiment_code', models.CharField(max_length=30, verbose_name='کدرهگیری(کدملی)')),
                ('selected_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان و تاریخ نوبت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False, verbose_name='آیا این نوبت ثبت شده است؟')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.insurancemodel', verbose_name='بیمه')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_auth.patientmodel', verbose_name='بیمار')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'نوبت نسخه ی الکترونیکی بیمار',
                'verbose_name_plural': 'نوبت نسخه ی الکترونیکی بیماران',
                'ordering': ['-created'],
            },
        ),
    ]
