# Generated by Django 4.1.3 on 2023-01-02 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0002_alter_appointmenttimemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
