# Generated by Django 4.1.3 on 2023-02-11 17:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0002_alter_exprimentresultmodel_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitturntimemodel',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, help_text='این قوانین در صفحه ی اول قبل از انجام مراحل رزرو اینترنتی نمایش داده میشود.', null=True, verbose_name='قوانین نوبت دهی'),
        ),
        migrations.AlterField(
            model_name='subunitmodel',
            name='have_2_box',
            field=models.BooleanField(default=False, help_text='در بخش نوبت دهی اینترنتی باعث میشود که کاربر به ۲ طریق مختلف رزرو اینترنتی انجام دهد.', verbose_name='آیا دو قسمتی است؟'),
        ),
    ]
