# Generated by Django 4.1.3 on 2023-01-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0002_appointmenttimemodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subunitmodel',
            old_name='category_ar',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='subunitmodel',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='subunitmodel',
            name='category_fa',
        ),
        migrations.RemoveField(
            model_name='subunitmodel',
            name='category_ru',
        ),
    ]
