# Generated by Django 4.1.3 on 2022-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0002_patientturnmodel_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitturntimemodel',
            name='rules',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین نوبت دهی'),
        ),
    ]
