# Generated by Django 4.1.3 on 2022-12-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0002_remove_priceappointmentmodel_price_free_and_more'),
        ('hospital_units', '0002_remove_limitturntimemodel_how_days_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttimemodel',
            name='price',
        ),
        migrations.AddField(
            model_name='appointmenttimemodel',
            name='insurances',
            field=models.ManyToManyField(to='hospital_setting.insurancemodel', verbose_name='بیمه ها'),
        ),
    ]
