# Generated by Django 4.1.3 on 2022-12-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0002_alter_unitmembermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
    ]
