# Generated by Django 4.1.3 on 2022-12-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_setting', '0004_alter_priceappointmentmodel_degree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_doctor', '0003_alter_doctormodel_degree_and_more'),
        ('hospital_units', '0002_remove_patientturnmodel_insurance_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttimemodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='appointmenttimemodel',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.priceappointmentmodel', verbose_name='تعرفه'),
        ),
        migrations.AlterField(
            model_name='appointmenttimemodel',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='اگر مقداری به این قسمت داده نشود در اینصورت بخش پزشکان انتخاب میشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='exprimentresultmodel',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='exprimentresultmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='onlinepaymentmodel',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.patientturnmodel', verbose_name='پرداخت کننده'),
        ),
        migrations.AlterField(
            model_name='patientturnmodel',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.appointmenttimemodel', verbose_name='زمان مشاوره'),
        ),
        migrations.AlterField(
            model_name='patientturnmodel',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_setting.insurancemodel', verbose_name='بیمه'),
        ),
        migrations.AlterField(
            model_name='patientturnmodel',
            name='reserver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رزرو کننده'),
        ),
    ]
