# Generated by Django 4.1.3 on 2022-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_remove_appointmenttimemodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttipmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='appointmenttipsmsmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='unitmembermodel',
            name='phone',
            field=models.CharField(default=0, max_length=100, verbose_name='شماره تلفن'),
        ),
    ]
