# Generated by Django 4.1.3 on 2023-01-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_rename_category_ar_subunitmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exprimentresultmodel',
            name='is_sent_sms',
        ),
    ]
