# Generated by Django 4.1.3 on 2022-12-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_alter_appointmenttimemodel_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='reserver',
        ),
    ]
