# Generated by Django 4.1.3 on 2022-12-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0002_logincodemodel_code_login'),
        ('hospital_units', '0003_alter_unitmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='patientturnmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='patientturnmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_auth.patientmodel', verbose_name='بیمار'),
        ),
    ]
