# Generated by Django 4.1.3 on 2023-01-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_electronicprescriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicprescriptionmodel',
            name='insurance',
        ),
    ]
