# Generated by Django 4.1.3 on 2023-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_alter_unitmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
