# Generated by Django 4.1.3 on 2023-01-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_doctor', '0002_initial'),
        ('hospital_units', '0004_alter_unitmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttimemodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک'),
        ),
    ]
