# Generated by Django 4.1.3 on 2022-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0004_remove_patientturnmodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttimemodel',
            name='reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد رزرو شده'),
        ),
    ]
