# Generated by Django 4.1.3 on 2022-12-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0004_alter_appointmenttipmodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprimentresultmodel',
            name='type',
            field=models.CharField(choices=[('experiment', 'آزمایش'), ('ctscan', 'تصویربرداری (سی تی اسکن)'), ('radiography_simple', 'تصویربرداری (رادیوگرافی ساده)'), ('radiography_special', 'تصویربرداری (رادیوگرافی تخصصی)'), ('mamography', 'تصویربرداری (ماموگرافی)'), ('sonography', 'تصویربرداری (سونوگرافی)')], max_length=50, verbose_name='نوع نتیجه'),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره مسیول'),
        ),
    ]
