# Generated by Django 4.1.3 on 2022-12-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0005_alter_exprimentresultmodel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttimemodel',
            name='tip_sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.appointmenttipsmsmodel', verbose_name='نکات نوبت دهی در پیامک'),
        ),
    ]
