# Generated by Django 4.1.3 on 2023-01-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_doctor', '0002_initial'),
        ('hospital_units', '0005_alter_electronicprescriptionmodel_selected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicprescriptionmodel',
            name='code',
        ),
        migrations.AddField(
            model_name='electronicprescriptionmodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.doctormodel', verbose_name='پزشک'),
        ),
    ]
