# Generated by Django 4.1.3 on 2022-12-03 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام درمانگاه')),
            ],
            options={
                'verbose_name': 'درمانگاه',
                'verbose_name_plural': 'درمانگاه ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشک ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_code', models.IntegerField(verbose_name='کد نظام پزشکی')),
                ('position', models.TextField(max_length=500, verbose_name='موقعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_jobs.clinicmodel', verbose_name='کلینیک')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_jobs.doctormodel', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'عنوان تخصص',
                'verbose_name_plural': 'عناوین تخصص\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TitleSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تخصص')),
            ],
            options={
                'verbose_name': 'عنوان تخصص',
                'verbose_name_plural': 'عناوین تخصص\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorWorkTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک شنبه'), ('monday', 'دو شنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهار شنبه'), ('thursday', 'پنج شنبه'), ('friday', 'جمعه')], max_length=15, verbose_name='روز')),
                ('time', models.CharField(choices=[('6-8', '6-8'), ('8-10', '8-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20'), ('20-22', '20-22')], max_length=15, verbose_name='زمان')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_jobs.doctorskillmodel', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'زمان کاری پزشک',
                'verbose_name_plural': 'زمان\u200cهای کاری پزشکان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorVacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField(default=django.utils.timezone.now, verbose_name='از تاریخ')),
                ('to_time', models.DateField(default=django.utils.timezone.now, verbose_name='تا تاریخ')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_jobs.doctorskillmodel', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'زمان مرخصی پزشک',
                'verbose_name_plural': 'زمان\u200cهای مرخصی پزشکان',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='doctorskillmodel',
            name='skill_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_jobs.titleskillmodel', verbose_name='عنوان تخصص'),
        ),
    ]
