# Generated by Django 4.1.3 on 2022-12-06 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_doctor', '0001_initial'),
        ('hospital_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTimeListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=20, null=True, verbose_name='نام بخش')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ روز')),
                ('time', models.CharField(choices=[('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-13', '12-13'), ('13-14', '13-14'), ('14-15', '14-15'), ('15-16', '15-16'), ('16-17', '16-17'), ('17-18', '17-18'), ('18-19', '18-19'), ('19-20', '19-20'), ('20-21', '20-21'), ('21-22', '21-22'), ('22-23', '22-23'), ('23-24', '23-24')], max_length=15, verbose_name='بازه ی زمانی')),
                ('time_of_one_visit', models.PositiveIntegerField(default=5, verbose_name='زمان ویزیت هر بیمار با این بخش/پزشک')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_doctor.doctormodel', verbose_name='پزشک')),
                ('insurance', models.ManyToManyField(to='hospital_setting.insurancemodel', verbose_name='بیمه ها')),
            ],
            options={
                'verbose_name': 'زمان نوبتدهی',
                'verbose_name_plural': 'لیست زمان های نوبتدهی',
                'ordering': ['-id'],
            },
        ),
    ]
