# Generated by Django 4.1.3 on 2022-11-30 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefactorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('is_founder', models.BooleanField(default=False, verbose_name='بنیانگذار است؟')),
                ('about', models.TextField(verbose_name='درباره ی نیکوکار')),
            ],
            options={
                'verbose_name': 'خیر و نیکوکار',
                'verbose_name_plural': 'خیرین و نیکوکاران',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن ارتباط')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل کاربر')),
                ('phone', models.BigIntegerField(verbose_name='شماره تلفن')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ارتباط')),
                ('is_read', models.BooleanField(default=False, verbose_name='بررسی شده یا نه')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تماس مخاطب',
                'verbose_name_plural': 'تماس های مخاطبان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=500, verbose_name='متن')),
                ('is_from_boss', models.BooleanField(default=False, verbose_name='آیا این متن از سمت ریاست است؟')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار پست')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PeopleAidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل کاربر')),
                ('phone', models.BigIntegerField(verbose_name='شماره تلفن')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ کمک شده')),
                ('date_of_aid', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ کمک')),
            ],
            options={
                'verbose_name': 'کمک مردمی',
                'verbose_name_plural': 'کمک های مردمی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='توسط کاربر خوانده شده؟')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_contact.notificationmodel', verbose_name='اعلان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان برای کاربر',
                'verbose_name_plural': 'اعلان برای کاربران',
                'ordering': ['-id'],
            },
        ),
    ]
