# Generated by Django 4.1.3 on 2022-12-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_contact', '0001_initial'),
        ('hospital_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsightmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_units.unitmodel', verbose_name='بخش'),
        ),
        migrations.AddField(
            model_name='notificationusermodel',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_contact.notificationmodel', verbose_name='اعلان'),
        ),
        migrations.AddField(
            model_name='notificationusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='hireformmodel',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_contact.careersmodel', verbose_name='موقعیت شغلی'),
        ),
        migrations.AddField(
            model_name='hireformmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='criticismsuggestionmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_units.unitmodel', verbose_name='نام بخش'),
        ),
        migrations.AddField(
            model_name='careersmodel',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_doctor.degreemodel', verbose_name='نوع مدرک'),
        ),
        migrations.AddField(
            model_name='careersmodel',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_doctor.titleskillmodel', verbose_name='تخصص'),
        ),
        migrations.AddField(
            model_name='careersmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_units.unitmodel', verbose_name='بخش مربوطه'),
        ),
    ]
