# Generated by Django 4.1.3 on 2023-01-24 14:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='متن'),
        ),
    ]
