# Generated by Django 4.1.3 on 2023-01-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireformmodel',
            name='user',
        ),
    ]
