# Generated by Django 4.1.3 on 2022-12-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان موقعیت'),
        ),
        migrations.AlterField(
            model_name='hireformmodel',
            name='burthday_place',
            field=models.CharField(max_length=100, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='hireformmodel',
            name='direct',
            field=models.CharField(max_length=100, verbose_name='معرف'),
        ),
        migrations.AlterField(
            model_name='hireformmodel',
            name='education',
            field=models.CharField(max_length=100, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='hireformmodel',
            name='uni',
            field=models.CharField(max_length=100, verbose_name='نام دانشگاه'),
        ),
    ]
