# Generated by Django 4.1.3 on 2023-02-26 17:29

import ckeditor.fields
from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_fa', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_en', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_ar', models.CharField(max_length=100, verbose_name='نام')),
                ('first_name_ru', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name_fa', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('last_name_en', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('last_name_ar', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('last_name_ru', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('profile', models.ImageField(upload_to=extentions.utils.famous_profile_image_path, verbose_name='تصویر')),
                ('desc_fa', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('desc_en', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('desc_ar', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('desc_ru', ckeditor.fields.RichTextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'چهره سرشناس مراجعه کننده',
                'verbose_name_plural': 'چهره های سرشناس مراجعه کننده',
                'ordering': ['-id'],
            },
        ),
    ]
