# Generated by Django 4.1.3 on 2023-01-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careersmodel',
            old_name='desc_ar',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='careersmodel',
            old_name='expriment_ar',
            new_name='expriment',
        ),
        migrations.RenameField(
            model_name='careersmodel',
            old_name='title_ar',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='description_ar',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='title_ar',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='peopleaidmodel',
            old_name='name_ar',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='desc_fa',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='expriment_en',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='expriment_fa',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='expriment_ru',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='careersmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='peopleaidmodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='peopleaidmodel',
            name='name_fa',
        ),
        migrations.RemoveField(
            model_name='peopleaidmodel',
            name='name_ru',
        ),
    ]
