# Generated by Django 4.1.3 on 2022-12-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0003_alter_appointmenttimemodel_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_doctor', '0003_alter_doctormodel_degree_and_more'),
        ('hospital_contact', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersmodel',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.degreemodel', verbose_name='نوع مدرک'),
        ),
        migrations.AlterField(
            model_name='careersmodel',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_doctor.titleskillmodel', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='careersmodel',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش مربوطه'),
        ),
        migrations.AlterField(
            model_name='criticismsuggestionmodel',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='hireformmodel',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_contact.careersmodel', verbose_name='موقعیت شغلی'),
        ),
        migrations.AlterField(
            model_name='hireformmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='notificationusermodel',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_contact.notificationmodel', verbose_name='اعلان'),
        ),
        migrations.AlterField(
            model_name='notificationusermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='patientsightmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='patientsightmodel',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_units.unitmodel', verbose_name='بخش'),
        ),
    ]
