# Generated by Django 4.1.3 on 2023-01-22 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0003_remove_hireformmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireformmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
