# Generated by Django 4.1.3 on 2023-01-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0003_notificationmodel_is_read_notificationmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='publish_time',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
    ]
