# Generated by Django 4.1.3 on 2023-04-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0003_workshopmodel_desc_ar_workshopmodel_desc_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopmodel',
            name='nums',
        ),
    ]
