# Generated by Django 4.1.3 on 2023-01-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0003_alter_notificationmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireformmodel',
            old_name='burthday_date',
            new_name='birthday_date',
        ),
    ]
