# Generated by Django 4.1.3 on 2023-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0004_rename_burthday_date_hireformmodel_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireformmodel',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کدملی'),
        ),
    ]
