# Generated by Django 4.1.3 on 2023-01-24 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0005_alter_hireformmodel_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
