# Generated by Django 4.1.3 on 2023-02-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0006_alter_contactusmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireformmodel',
            old_name='burthday_place',
            new_name='birthday_place',
        ),
    ]
