# Generated by Django 4.1.3 on 2023-02-02 17:11

from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contact', '0007_rename_burthday_place_hireformmodel_birthday_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=extentions.utils.career_image_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='criticismsuggestionmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل کاربر'),
        ),
    ]
