# Generated by Django 4.1.3 on 2022-11-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=0, verbose_name='شماره تلفن'),
        ),
    ]
