# Generated by Django 4.1.3 on 2023-01-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_newsletter_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='is_contact_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل ارتباطات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_appointment_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل نوبت دهی آنلاین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blog_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل بلاگ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_doctor_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل پزشکی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_expriment_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل ثبت آزمایش و تصویربرداری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_news_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل اخبار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_note_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل نوت پزشکی'),
        ),
    ]
