# Generated by Django 4.1.3 on 2022-12-19 12:58

from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincodemodel',
            name='code_login',
            field=models.CharField(default=extentions.utils.get_links_code, max_length=30, verbose_name='کد ورود'),
        ),
    ]
