# Generated by Django 4.1.3 on 2023-02-05 19:21

from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdmodel',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='ipdmodel',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='ipdmodel',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=extentions.utils.ipd_doc_image_path, verbose_name='مستندات'),
        ),
    ]
