# Generated by Django 4.1.3 on 2023-01-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logincodemodel',
            name='usage',
        ),
    ]
