# Generated by Django 4.1.3 on 2022-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_appointment_manager',
            field=models.BooleanField(default=False, verbose_name='قابلیت دسترسی به نوبت دهی آنلاین'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blog_manager',
            field=models.BooleanField(default=False, verbose_name='قابلیت پست گذاشتن'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_expriment_manager',
            field=models.BooleanField(default=False, verbose_name='قابلیت گذاشتن جواب آزمایش و تصویربرداری های بیمار'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_news_manager',
            field=models.BooleanField(default=False, verbose_name='قابلیت خبر گذاشتن'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_note_manager',
            field=models.BooleanField(default=False, verbose_name='قابلیت نوشتن نوت پزشکی'),
        ),
    ]
