# Generated by Django 4.1.3 on 2022-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0002_logincodemodel_code_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='age',
            field=models.PositiveIntegerField(verbose_name='سن'),
        ),
    ]
