# Generated by Django 4.1.3 on 2022-12-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0002_user_is_appointment_manager_user_is_blog_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincodemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
