# Generated by Django 4.1.3 on 2023-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0002_ipdmodel_state_alter_ipdmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ipd_manager',
            field=models.BooleanField(default=False, verbose_name='مدیریت پنل IPD'),
        ),
    ]
