# Generated by Django 4.1.3 on 2022-11-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fixed_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=20, verbose_name='شماره تلفن'),
        ),
    ]
