# Generated by Django 4.1.3 on 2022-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0003_alter_logincodemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fixed_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_famous',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_intenational',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_send_sms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_balance',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=7, verbose_name='جنسیت'),
        ),
    ]
