# Generated by Django 4.1.3 on 2023-02-06 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0003_user_is_ipd_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
