# Generated by Django 4.1.3 on 2023-02-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0004_alter_ipdmodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPDModel',
        ),
    ]
