# Generated by Django 4.1.3 on 2023-03-15 21:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hospital_extentions.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='شماره تلفن')),
                ('code', models.IntegerField(default=hospital_extentions.utils.get_random_code, unique=True, verbose_name='کد')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید کد')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای کد')),
                ('is_use', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
                ('expire_mission', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای عملیات')),
            ],
            options={
                'verbose_name': 'کد احراز هویت ipd',
                'verbose_name_plural': 'کدهای احراز هویت ipd',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IPDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.IntegerField(default=hospital_extentions.utils.get_patient_tracking_code, null=True, verbose_name='کد')),
                ('username', models.CharField(max_length=10, verbose_name='شماره پاسپورت/کدملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=7, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='سن')),
                ('description', ckeditor.fields.RichTextField(verbose_name='شرح بیماری')),
                ('document', models.FileField(blank=True, null=True, upload_to=hospital_extentions.utils.ipd_doc_image_path, verbose_name='مستندات')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='شهر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پاسخ')),
                ('is_answered', models.BooleanField(default=False, verbose_name='آیا جواب داده شده است؟')),
                ('doctor_answerer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پزشک پاسخگو')),
            ],
            options={
                'verbose_name': 'بیمار بین\u200cالملل',
                'verbose_name_plural': 'بیماران بین\u200cالملل',
                'ordering': ['-id'],
            },
        ),
    ]
