# Generated by Django 4.1.3 on 2023-02-06 12:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import extentions.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='شماره پاسپورت / کدملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=7, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='سن')),
                ('description', ckeditor.fields.RichTextField(verbose_name='شرح بیماری')),
                ('document', models.FileField(blank=True, null=True, upload_to=extentions.utils.ipd_doc_image_path, verbose_name='مستندات')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='شهر')),
                ('is_answered', models.BooleanField(default=False, verbose_name='آیا جواب داده شده است؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بیمار بین الملل',
                'verbose_name_plural': 'بیماران بین الملل',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IPDCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=extentions.utils.get_random_code, verbose_name='کد')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید کد')),
                ('expire_date', models.DateTimeField(blank=True, help_text='این فیلد لازم نیست پر شود. بعد از ثبت رکورد بصورت اتوماتیک ثبت میشود.', null=True, verbose_name='تاریخ انقضای کد')),
                ('is_use', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
                ('ipd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_ipd.ipdmodel', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'کد احراز هویت ipd',
                'verbose_name_plural': 'کدهای احراز هویت ipd',
                'ordering': ['-id'],
            },
        ),
    ]
