# Generated by Django 4.1.3 on 2023-02-06 13:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_ipd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdcodemodel',
            name='ipd',
        ),
        migrations.AddField(
            model_name='ipdcodemodel',
            name='expire_mission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای عملیات'),
        ),
        migrations.AddField(
            model_name='ipdcodemodel',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='ipdmodel',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
        migrations.AddField(
            model_name='ipdmodel',
            name='doctor_answerer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پزشک پاسخگو'),
        ),
        migrations.AlterField(
            model_name='ipdcodemodel',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای کد'),
        ),
    ]
