# Generated by Django 4.1.3 on 2023-01-10 11:39

from django.db import migrations, models
import extentions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نظر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش داده شود؟')),
                ('is_read', models.BooleanField(default=False, verbose_name='توسط نویسنده خوانده شده؟')),
            ],
            options={
                'verbose_name': 'نظر کاربر برای بلاگ',
                'verbose_name_plural': 'نظرات کاربران برای بلاگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=extentions.utils.blog_gallery_image_path, verbose_name='تصویر')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک ویدیو')),
            ],
            options={
                'verbose_name': 'گالری بلاگ',
                'verbose_name_plural': 'گالری بلاگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike', models.CharField(choices=[('like', 'لایک'), ('dislike', 'دیسلایک')], max_length=10, verbose_name='لایک یا دیسلایک')),
            ],
            options={
                'verbose_name': 'لایک یا دیسلایک بلاگ',
                'verbose_name_plural': 'لایک یا دیسلایک بلاگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditEduModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=extentions.utils.get_credit_edu_code, unique=True, verbose_name='مقدار در url')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=extentions.utils.credit_edu_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'آموزش اعتبار بخشی',
                'verbose_name_plural': 'آموزش های اعتباربخشی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_fa', models.TextField(max_length=400, verbose_name='متن')),
                ('text_en', models.TextField(max_length=400, verbose_name='متن')),
                ('text_ar', models.TextField(max_length=400, verbose_name='متن')),
                ('text_ru', models.TextField(max_length=400, verbose_name='متن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوت پزشکی',
                'verbose_name_plural': 'نوت های پزشکی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PampheletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=extentions.utils.pamphelet_image_path, verbose_name='تصویر')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پمفلت آموزشی',
                'verbose_name_plural': 'پمفلت های آموزشی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=extentions.utils.get_blog_code, unique=True, verbose_name='مقدار در url')),
                ('image', models.ImageField(upload_to=extentions.utils.blog_image_path, verbose_name='تصویر')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=extentions.utils.blog_pdf_image_path, verbose_name='پی دی اف بلاگ')),
                ('qr_img', models.ImageField(blank=True, null=True, upload_to=extentions.utils.blog_qrcode_image_path, verbose_name='تصویر کد QR')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک ویدیو')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=200, verbose_name='عنوان')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name='زمان خواندن')),
                ('desc_fa', models.TextField(verbose_name='متن مقاله')),
                ('desc_en', models.TextField(verbose_name='متن مقاله')),
                ('desc_ar', models.TextField(verbose_name='متن مقاله')),
                ('desc_ru', models.TextField(verbose_name='متن مقاله')),
                ('short_desc_fa', models.CharField(max_length=500, verbose_name='متن کوتاه')),
                ('short_desc_en', models.CharField(max_length=500, verbose_name='متن کوتاه')),
                ('short_desc_ar', models.CharField(max_length=500, verbose_name='متن کوتاه')),
                ('short_desc_ru', models.CharField(max_length=500, verbose_name='متن کوتاه')),
                ('is_publish', models.BooleanField(default=False, verbose_name='آیا منتشر شود؟')),
                ('is_emailed', models.BooleanField(default=False, verbose_name='آیا ایمیل شده است؟')),
                ('is_activate', models.BooleanField(default=False, verbose_name='آیا پست از نظر تولید کننده محتوا تایید شده است؟')),
                ('is_likeable', models.BooleanField(default=True, verbose_name='امکان لایک دارد؟')),
                ('is_dislikeable', models.BooleanField(default=True, verbose_name='امکان دیسلایک دارد؟')),
                ('is_commentable', models.BooleanField(default=True, verbose_name='امکان کامنت دارد؟')),
                ('categories', models.ManyToManyField(to='hospital_blog.categorymodel', verbose_name='دسته بندی ها')),
                ('gallery', models.ManyToManyField(to='hospital_blog.bloggallerymodel', verbose_name='گالری بلاگ')),
                ('tags', models.ManyToManyField(to='hospital_blog.tagmodel', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
