# Generated by Django 4.1.3 on 2023-04-20 19:18

import ckeditor.fields
from django.db import migrations, models
import hospital_extentions.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', ckeditor.fields.RichTextField(verbose_name='نظر')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='نام\u200cخانوادگی')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='شماره تلفن')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش داده شود؟')),
                ('is_read', models.BooleanField(default=False, verbose_name='توسط نویسنده خوانده شده؟')),
            ],
            options={
                'verbose_name': 'نظر کاربر برای بلاگ',
                'verbose_name_plural': 'نظرات کاربران برای بلاگ\u200cها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BlogGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hospital_extentions.utils.blog_gallery_image_path, verbose_name='تصویر')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک ویدیو')),
            ],
            options={
                'verbose_name': 'گالری بلاگ',
                'verbose_name_plural': 'گالری بلاگ\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('like_dislike', models.CharField(choices=[('like', 'لایک'), ('dislike', 'دیسلایک')], max_length=10, verbose_name='لایک یا دیسلایک')),
            ],
            options={
                'verbose_name': 'لایک یا دیسلایک بلاگ',
                'verbose_name_plural': 'لایک یا دیسلایک بلاگ\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditEduModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=hospital_extentions.utils.get_credit_edu_code, unique=True, verbose_name='مقدار در url')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=hospital_extentions.utils.credit_edu_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'اعتباربخشی',
                'verbose_name_plural': 'اعتباربخشی\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text_fa', models.TextField(max_length=400, verbose_name='متن')),
                ('text_en', models.TextField(max_length=400, verbose_name='متن')),
                ('text_ar', models.TextField(max_length=400, verbose_name='متن')),
                ('text_ru', models.TextField(max_length=400, verbose_name='متن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوت پزشکی',
                'verbose_name_plural': 'نوت\u200cهای پزشکی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PampheletModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=hospital_extentions.utils.pamphelet_image_path, verbose_name='تصویر')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پمفلت آموزشی',
                'verbose_name_plural': 'پمفلت\u200cهای آموزشی',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SMSTextModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=400, verbose_name='متن')),
                ('receivers', models.CharField(choices=[('patients', 'بیماران بخش نوبت اینترنتی'), ('patientsipd', 'بیماران بخش ipd'), ('doctors', 'پزشکان'), ('bloggers', 'ادمین\u200cهای بخش پست'), ('news', 'ادمین\u200cهای بخش خبر'), ('lab', 'ادمین\u200cهای بخش ثبت آزمایش و تصویربرداری'), ('appointment', 'ادمین\u200cهای پذیرش اینترنتی'), ('contacts', 'ادمین\u200cهای بخش ارتباطات'), ('ipdmanager', 'ادمین\u200cهای بخش ipd'), ('all', 'همه (پزشکان و بیماران و کاربران)')], max_length=20, verbose_name='جامعه\u200cی دریافت کننده\u200cی پیامک')),
                ('is_sent', models.BooleanField(default=False, verbose_name='آیا پیامک به اعضای نام\u200cبرده ارسال شود؟')),
                ('is_sent_sms', models.BooleanField(default=False, editable=False, verbose_name='آیا پیامک ارسال شده است؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=100, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=hospital_extentions.utils.get_blog_code, unique=True, verbose_name='مقدار در url')),
                ('image', models.ImageField(upload_to=hospital_extentions.utils.blog_image_path, verbose_name='تصویر')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=hospital_extentions.utils.blog_pdf_image_path, verbose_name='پی\u200cدی\u200cاف بلاگ')),
                ('qr_img', models.ImageField(blank=True, editable=False, null=True, upload_to=hospital_extentions.utils.blog_qrcode_image_path, verbose_name='تصویر کد QR')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک ویدیو')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_ru', models.CharField(max_length=200, verbose_name='عنوان')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name='زمان خواندن')),
                ('desc_fa', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('desc_en', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('desc_ar', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('desc_ru', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('short_desc_fa', models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه')),
                ('short_desc_en', models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه')),
                ('short_desc_ar', models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه')),
                ('short_desc_ru', models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه')),
                ('is_publish', models.BooleanField(default=False, help_text='اگر این تیک فعال باشد بعد از ذخیره شدن ایمیل برای اعضای خبرنامه ارسال میشود.', verbose_name='آیا منتشر شود؟')),
                ('is_emailed', models.BooleanField(default=False, editable=False, verbose_name='آیا ایمیل شده است؟')),
                ('is_likeable', models.BooleanField(default=True, verbose_name='امکان لایک دارد؟')),
                ('is_dislikeable', models.BooleanField(default=True, verbose_name='امکان دیسلایک دارد؟')),
                ('is_commentable', models.BooleanField(default=True, verbose_name='امکان کامنت دارد؟')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ManyToManyField(to='hospital_blog.categorymodel', verbose_name='دسته بندی\u200cها')),
                ('gallery', models.ManyToManyField(blank=True, to='hospital_blog.bloggallerymodel', verbose_name='گالری بلاگ')),
                ('tags', models.ManyToManyField(to='hospital_blog.tagmodel', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ['-created'],
            },
        ),
    ]
