# Generated by Django 4.1.3 on 2023-04-20 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_blog', '0001_initial'),
        ('hospital_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='units',
            field=models.ManyToManyField(blank=True, to='hospital_units.unitmodel', verbose_name='بخش\u200cها'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='bloglikemodel',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_blog.blogmodel', verbose_name='بلاگ'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_blog.blogmodel', verbose_name='بلاگ'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_blog.blogcommentmodel', verbose_name='پاسخ'),
        ),
    ]
