# Generated by Django 4.1.3 on 2022-11-30 12:23

import Extentions.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نظر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش داده شود؟')),
                ('is_read', models.BooleanField(default=False, verbose_name='توسط نویسنده خوانده شده؟')),
            ],
            options={
                'verbose_name': 'نظر کاربر برای بلاگ',
                'verbose_name_plural': 'نظرات کاربران برای بلاگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('file_type', models.CharField(choices=[('video', 'ویدیو'), ('image', 'تصویر')], max_length=20, verbose_name='نوع فایل')),
                ('file', models.FileField(upload_to=Extentions.utils.blog_gallery_image_path, verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'گالری بلاگ',
                'verbose_name_plural': 'گالری بلاگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike', models.CharField(choices=[('like', 'لایک'), ('dislike', 'دیسلایک')], max_length=10, verbose_name='لایک یا دیسلایک')),
            ],
            options={
                'verbose_name': 'لایک یا دیسلایک بلاگ',
                'verbose_name_plural': 'لایک یا دیسلایک بلاگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=Extentions.utils.get_blog_code, unique=True, verbose_name='مقدار در url')),
                ('image', models.ImageField(upload_to=Extentions.utils.blog_image_path, verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to=Extentions.utils.blog_image_path, verbose_name='ویدیو')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name='زمان خواندن')),
                ('desc', models.TextField(verbose_name='متن مقاله')),
                ('short_desc', models.CharField(max_length=500, verbose_name='متن کوتاه')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار پست')),
                ('is_activate', models.BooleanField(default=False, verbose_name='آیا پست از نظر تولید کننده محتوا تایید شده است؟')),
                ('is_likeable', models.BooleanField(default=True, verbose_name='امکان لایک دارد؟')),
                ('is_dislikeable', models.BooleanField(default=True, verbose_name='امکان دیسلایک دارد؟')),
                ('is_commentable', models.BooleanField(default=True, verbose_name='امکان کامنت دارد؟')),
                ('is_educational', models.BooleanField(default=False, verbose_name='آیا این بلاگ آموزشی است؟')),
                ('categories', models.ManyToManyField(to='hospital_blog.categorymodel', verbose_name='دسته بندی ها')),
                ('gallery', models.ManyToManyField(blank=True, null=True, to='hospital_blog.bloggallerymodel', verbose_name='گالری بلاگ')),
                ('tags', models.ManyToManyField(to='hospital_blog.tagmodel', verbose_name='تگ ها')),
                ('writer_contentproducer', models.ForeignKey(help_text='اگر این فیلد پر بشود یعنی تولید کننده ی این پست یک شخص تولید کننده ی محتوا بوده است.', on_delete=django.db.models.deletion.CASCADE, to='hospital_auth.contentproducermodel', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='newslikemodel',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newslikemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='writer_contentproducer',
        ),
        migrations.DeleteModel(
            name='NewsCommentModel',
        ),
        migrations.DeleteModel(
            name='NewsGalleryModel',
        ),
        migrations.DeleteModel(
            name='NewsLikeModel',
        ),
        migrations.DeleteModel(
            name='NewsModel',
        ),
        migrations.AddField(
            model_name='bloglikemodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_blog.blogmodel', verbose_name='بلاگ'),
        ),
        migrations.AddField(
            model_name='bloglikemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_blog.blogmodel', verbose_name='بلاگ'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_blog.blogcommentmodel', verbose_name='پاسخ'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
