# Generated by Django 4.1.3 on 2022-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0002_blogcommentmodel_bloggallerymodel_bloglikemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalNoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='متن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوت پزشکی',
                'verbose_name_plural': 'نوت های پزشکی',
                'ordering': ['-id'],
            },
        ),
    ]
