# Generated by Django 4.1.3 on 2023-01-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='is_activate',
        ),
    ]
