# Generated by Django 4.1.3 on 2022-11-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0003_medicalnotemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='gallery',
            field=models.ManyToManyField(to='hospital_blog.bloggallerymodel', verbose_name='گالری بلاگ'),
        ),
    ]
