# Generated by Django 4.1.3 on 2023-01-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0003_remove_blogmodel_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloggallerymodel',
            old_name='title_ar',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bloggallerymodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='bloggallerymodel',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='bloggallerymodel',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='is_emailed',
            field=models.BooleanField(default=False, editable=False, verbose_name='آیا ایمیل شده است؟'),
        ),
    ]
