# Generated by Django 4.1.3 on 2023-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0003_alter_blogmodel_qr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='is_publish',
            field=models.BooleanField(default=False, help_text='اگر این تیک فعال باشد بعد از ذخیره شدن ایمیل برای اعضای خبرنامه ارسال میشود.', verbose_name='آیا منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='short_desc_ar',
            field=models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='short_desc_en',
            field=models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='short_desc_fa',
            field=models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='short_desc_ru',
            field=models.TextField(help_text='سعی کنید خلاصه ای بنویسید که شامل کلمات کلیدی باشد.', max_length=500, verbose_name='متن کوتاه'),
        ),
    ]
