# Generated by Django 4.1.3 on 2023-01-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_units', '0005_rename_tips_ar_appointmenttipmodel_tips_and_more'),
        ('hospital_blog', '0004_rename_title_ar_bloggallerymodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='units',
            field=models.ManyToManyField(blank=True, null=True, to='hospital_units.unitmodel', verbose_name='بخش ها'),
        ),
    ]
