# Generated by Django 4.1.3 on 2023-02-11 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0004_alter_blogmodel_is_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTextModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text_fa', models.TextField(max_length=400, verbose_name='متن')),
                ('text_en', models.TextField(max_length=400, verbose_name='متن')),
                ('text_ar', models.TextField(max_length=400, verbose_name='متن')),
                ('text_ru', models.TextField(max_length=400, verbose_name='متن')),
                ('receivers', models.CharField(choices=[('patients', 'بیماران بخش نوبت اینترنتی'), ('patientsipd', 'بیماران بخش ipd'), ('doctors', 'پزشکان'), ('bloggers', 'ادمین های بخش پست'), ('news', 'ادمین های بخش خبر'), ('lab', 'ادمین های بخش ثبت آزمایش و تصویربرداری'), ('appointment', 'ادمین های پذیرش اینترنتی'), ('contacts', 'ادمین های بخش ارتباطات'), ('ipdmanager', 'ادمین های بخش ipd'), ('all', 'همه (پزشکان و بیماران و کاربران)')], max_length=20, verbose_name='جامعه ی دریافت کننده ی پیامک')),
                ('is_sent', models.BooleanField(default=False, verbose_name='آیا پیامک به اعضای نام برده ارسال شود؟')),
                ('is_sent_sms', models.BooleanField(default=False, editable=False, verbose_name='آیا پیامک ارسال شده ایت؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک ها',
                'ordering': ['-id'],
            },
        ),
    ]
