# Generated by Django 4.1.3 on 2023-02-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0005_smstextmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smstextmodel',
            old_name='text_en',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='smstextmodel',
            name='text_ar',
        ),
        migrations.RemoveField(
            model_name='smstextmodel',
            name='text_fa',
        ),
        migrations.RemoveField(
            model_name='smstextmodel',
            name='text_ru',
        ),
    ]
