# Generated by Django 4.1.3 on 2023-01-20 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_blog', '0008_remove_blogcommentmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
